### ISSUE TITLE
Potion refilling requires multiple potions

### ISSUE THREAD

**Issue by Mohl97** [HDest-Community/Arcanum#2]
the check for if you have a potion to refill from a barrel requires you have a potion in your inventory AND equipped. The problem being that if you have only one potion, it's temporarily removed from your inventory when it's equipped. You also can't simply have your potion in your inventory either, as then drinking straight from the barrel takes priority.

**Comment by Cryomundus** [comment]
Right, finally figured this one out. You can now refill a partially full potion as long as you have it in your inventory. Can't seem to get it to recognize if you're wielding it, so you'll have to swap to some other 'weapon' in order to refill it.
